import Link from "next/link"
import type { Metadata } from "next"
import "../policy-public.css"
import "../landing.css"

export const metadata: Metadata = {
  title: "Sample Policy — PolicyPen",
  description:
    "See a sample Privacy Policy generated by PolicyPen for Launchify, a fictional SaaS product. Get policies like this for your product in under 2 minutes.",
}

export default function DemoPage() {
  return (
    <div className="policy-page">
      {/* Nav */}
      <nav className="policy-nav">
        <Link href="/" className="policy-nav-name">PolicyPen</Link>
        <Link href="/sign-up" className="btn-primary" style={{ fontSize: 13, padding: "7px 16px" }}>
          Generate yours →
        </Link>
      </nav>

      <div className="policy-doc">

        {/* Notice banner */}
        <div style={{
          background: "#e8f3ec",
          border: "1px solid #b8d8c4",
          borderRadius: 6,
          padding: "12px 16px",
          marginBottom: 28,
          fontSize: 14,
          color: "#1a4a2e",
          lineHeight: 1.6,
        }}>
          <strong>Sample policy</strong> — Generated for Launchify, a fictional SaaS product.{" "}
          <Link href="/sign-up" style={{ color: "#1a4a2e", fontWeight: 600 }}>
            Sign up free
          </Link>{" "}
          to generate policies for your own product in under 2 minutes.
        </div>

        {/* Tab strip */}
        <div className="policy-tabs">
          <button className="policy-tab active">Privacy Policy</button>
          <button className="policy-tab" disabled style={{ opacity: 0.45, cursor: "not-allowed" }} title="Sign up to unlock">Terms of Service</button>
          <button className="policy-tab" disabled style={{ opacity: 0.45, cursor: "not-allowed" }} title="Sign up to unlock">Cookie Policy</button>
          <button className="policy-tab" disabled style={{ opacity: 0.45, cursor: "not-allowed" }} title="Sign up to unlock">Refund Policy</button>
        </div>

        {/* Policy header */}
        <div className="policy-single-header">
          <h1>Privacy Policy</h1>
          <div className="policy-meta">
            <span>Effective Date: January 1, 2025</span>
            <span>Version 1</span>
          </div>
        </div>

        {/* Policy content */}
        <div className="policy-content">

          <p>
            This Privacy Policy describes how Launchify (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) collects,
            uses, and shares information about you when you use our project management platform at launchify.app
            (the &ldquo;Service&rdquo;). By using the Service, you agree to the collection and use of information
            in accordance with this policy.
          </p>

          <h2>1. Information We Collect</h2>

          <h3>Information you provide directly</h3>
          <p>
            When you create an account or use our Service, we collect information you provide directly to us, including:
          </p>
          <ul>
            <li>Name and email address</li>
            <li>Payment information (processed by Stripe; we do not store card numbers)</li>
            <li>Profile information such as your company name, job title, and profile photo</li>
            <li>Content you create, upload, or share through the Service (project data, tasks, comments, attachments)</li>
            <li>Communications you send us, such as support requests or feedback</li>
          </ul>

          <h3>Information collected automatically</h3>
          <p>
            When you use the Service, we automatically collect certain information about your device and usage, including:
          </p>
          <ul>
            <li>Log data: IP address, browser type and version, pages visited, time and date of your visit, and time spent on pages</li>
            <li>Device information: hardware model, operating system, unique device identifiers</li>
            <li>Usage analytics: features you use, actions you take, and settings you choose</li>
            <li>Cookies and similar tracking technologies (see Section 5)</li>
          </ul>

          <h3>Information from third parties</h3>
          <p>
            We may receive information about you from third parties, such as when you sign in using Google or GitHub
            OAuth, or when a team member invites you to a workspace.
          </p>

          <h2>2. How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Provide, maintain, and improve the Service</li>
            <li>Process transactions and send related information, including receipts and invoices</li>
            <li>Send you technical notices, security alerts, and administrative messages</li>
            <li>Respond to your comments, questions, and requests</li>
            <li>Send marketing communications (you can opt out at any time)</li>
            <li>Monitor and analyze usage trends to improve user experience</li>
            <li>Detect, investigate, and prevent fraudulent transactions and abuse</li>
            <li>Comply with legal obligations</li>
          </ul>

          <p>
            <strong>Legal basis for processing (EU/UK users):</strong> We process your personal data on the basis of
            your consent (where you have given it), the performance of a contract between you and Launchify, our
            legitimate interests (such as improving the Service and preventing fraud), and compliance with legal
            obligations.
          </p>

          <h2>3. Information Sharing</h2>
          <p>We do not sell your personal information. We share your information only in the following circumstances:</p>
          <ul>
            <li>
              <strong>Service providers:</strong> We share information with third-party vendors who help us operate the
              Service, including cloud hosting (AWS), payment processing (Stripe), email delivery (Postmark), and
              analytics (Mixpanel). These vendors are contractually obligated to use your data only to perform services
              on our behalf.
            </li>
            <li>
              <strong>Team members:</strong> Content you share within a workspace is visible to other members of that
              workspace, as intended by the Service&rsquo;s collaboration features.
            </li>
            <li>
              <strong>Legal requirements:</strong> We may disclose information if required by law, regulation, or
              court order, or to protect the rights, property, or safety of Launchify, our users, or the public.
            </li>
            <li>
              <strong>Business transfers:</strong> If Launchify is acquired or merges with another company, your
              information may be transferred as part of that transaction.
            </li>
          </ul>

          <h2>4. Data Retention</h2>
          <p>
            We retain your information for as long as your account is active or as needed to provide the Service.
            If you close your account, we will delete or anonymize your information within 90 days, except where
            we are required to retain it for legal, tax, or audit purposes. Project data may be retained for up to
            30 days after deletion to allow recovery in case of accidental deletion.
          </p>

          <h2>5. Cookies and Tracking Technologies</h2>
          <p>
            We use cookies and similar tracking technologies to collect information about your use of the Service.
            Cookies are small data files stored on your device. We use:
          </p>
          <ul>
            <li><strong>Strictly necessary cookies:</strong> Required for the Service to function (session management, authentication)</li>
            <li><strong>Analytics cookies:</strong> Help us understand how you use the Service (e.g., Mixpanel)</li>
            <li><strong>Preference cookies:</strong> Remember your settings and preferences</li>
          </ul>
          <p>
            You can control cookies through your browser settings. Blocking strictly necessary cookies may prevent
            the Service from functioning correctly. See our Cookie Policy for full details.
          </p>

          <h2>6. Your Rights and Choices</h2>
          <p>Depending on your location, you may have certain rights regarding your personal information:</p>
          <ul>
            <li><strong>Access:</strong> Request a copy of the personal data we hold about you</li>
            <li><strong>Correction:</strong> Update inaccurate or incomplete information</li>
            <li><strong>Deletion:</strong> Request deletion of your personal data</li>
            <li><strong>Portability:</strong> Receive your data in a machine-readable format</li>
            <li><strong>Objection:</strong> Object to processing based on legitimate interests</li>
            <li><strong>Restriction:</strong> Request that we restrict processing of your data</li>
            <li><strong>Withdrawal of consent:</strong> Withdraw consent at any time where processing is based on consent</li>
          </ul>
          <p>
            To exercise any of these rights, contact us at <a href="mailto:privacy@launchify.app">privacy@launchify.app</a>.
            We will respond within 30 days. We may need to verify your identity before processing your request.
          </p>

          <h2>7. EU and UK Users — GDPR</h2>
          <p>
            If you are located in the European Economic Area (EEA) or United Kingdom, the following additional
            information applies:
          </p>
          <p>
            <strong>Data controller:</strong> Launchify Inc., 123 Market Street, San Francisco, CA 94105, USA.
          </p>
          <p>
            <strong>International transfers:</strong> Your information is processed on servers located in the United
            States. We transfer data to the US under the EU-US Data Privacy Framework and use Standard Contractual
            Clauses for other international transfers where required.
          </p>
          <p>
            <strong>Right to lodge a complaint:</strong> You have the right to lodge a complaint with your local data
            protection authority. In the UK, this is the Information Commissioner&rsquo;s Office (ICO) at ico.org.uk.
          </p>

          <h2>8. California Residents — CCPA</h2>
          <p>
            If you are a California resident, you have the following rights under the California Consumer Privacy Act
            (CCPA) and California Privacy Rights Act (CPRA):
          </p>
          <ul>
            <li>Right to know what personal information we collect, use, disclose, or sell</li>
            <li>Right to delete personal information we have collected</li>
            <li>Right to correct inaccurate personal information</li>
            <li>Right to opt out of the sale or sharing of personal information</li>
            <li>Right to non-discrimination for exercising your CCPA rights</li>
          </ul>
          <p>
            We do not sell personal information. To submit a request, email <a href="mailto:privacy@launchify.app">privacy@launchify.app</a> or
            call us at 1-800-LAUNCH-1. We will respond within 45 days.
          </p>

          <h2>9. Security</h2>
          <p>
            We implement industry-standard security measures to protect your information, including TLS encryption
            in transit, AES-256 encryption at rest, SOC 2 Type II compliance, regular security audits, and access
            controls limiting who can view your data within our organization. However, no method of transmission
            over the internet is 100% secure, and we cannot guarantee absolute security.
          </p>

          <h2>10. Children&rsquo;s Privacy</h2>
          <p>
            The Service is not directed to children under 16 years of age. We do not knowingly collect personal
            information from children under 16. If we become aware that a child under 16 has provided us with
            personal information, we will delete it promptly. If you believe a child has provided us their
            information, contact us at <a href="mailto:privacy@launchify.app">privacy@launchify.app</a>.
          </p>

          <h2>11. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. When we make material changes, we will notify
            you by email or by displaying a prominent notice in the Service at least 30 days before the changes
            take effect. Your continued use of the Service after the effective date constitutes your acceptance
            of the updated policy.
          </p>

          <h2>12. Contact Us</h2>
          <p>
            If you have questions about this Privacy Policy or our data practices, please contact us:
          </p>
          <ul>
            <li><strong>Email:</strong> <a href="mailto:privacy@launchify.app">privacy@launchify.app</a></li>
            <li><strong>Address:</strong> Launchify Inc., 123 Market Street, Suite 400, San Francisco, CA 94105</li>
            <li><strong>Data Protection Officer:</strong> <a href="mailto:dpo@launchify.app">dpo@launchify.app</a></li>
          </ul>

        </div>

        {/* Attribution */}
        <div className="policy-attribution">
          Generated by <Link href="/">PolicyPen</Link> — AI-powered legal policies for indie makers.
          <br />
          <Link href="/sign-up" style={{ display: "inline-block", marginTop: 12 }}>
            Generate policies for your product →
          </Link>
        </div>

      </div>
    </div>
  )
}
