/**
 * GET /api/export/[policy_id]?format=html|markdown
 *
 * Downloads a policy as an HTML or Markdown file.
 * Requires auth — users can only export their own policies (RLS enforced).
 */

import { auth } from "@clerk/nextjs/server"
import { NextRequest, NextResponse } from "next/server"
import { createServerClient } from "@/lib/supabase/client"

function htmlToMarkdown(html: string): string {
  return html
    .replace(/<h1[^>]*>([\s\S]*?)<\/h1>/gi, "# $1\n\n")
    .replace(/<h2[^>]*>([\s\S]*?)<\/h2>/gi, "## $1\n\n")
    .replace(/<h3[^>]*>([\s\S]*?)<\/h3>/gi, "### $1\n\n")
    .replace(/<h4[^>]*>([\s\S]*?)<\/h4>/gi, "#### $1\n\n")
    .replace(/<strong[^>]*>([\s\S]*?)<\/strong>/gi, "**$1**")
    .replace(/<b[^>]*>([\s\S]*?)<\/b>/gi, "**$1**")
    .replace(/<em[^>]*>([\s\S]*?)<\/em>/gi, "_$1_")
    .replace(/<i[^>]*>([\s\S]*?)<\/i>/gi, "_$1_")
    .replace(/<a[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/gi, "[$2]($1)")
    .replace(/<li[^>]*>([\s\S]*?)<\/li>/gi, "- $1\n")
    .replace(/<\/?(ul|ol)[^>]*>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim()
}

function wrapHtmlDocument(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
<style>
  body { max-width: 800px; margin: 40px auto; padding: 0 24px; font-family: Georgia, serif; font-size: 16px; line-height: 1.7; color: #1c1810; }
  h1 { font-size: 26px; margin-bottom: 8px; }
  h2 { font-size: 20px; margin-top: 32px; }
  h3 { font-size: 17px; margin-top: 24px; }
  p { margin: 0 0 14px; }
  ul, ol { margin: 0 0 14px; padding-left: 24px; }
  a { color: #1a4a2e; }
  .generated-by { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e4dfd3; font-size: 12px; color: #7a7060; font-family: sans-serif; }
</style>
</head>
<body>
${body}
<div class="generated-by">Generated by <a href="https://policypen.io">PolicyPen</a></div>
</body>
</html>`
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ policy_id: string }> }
) {
  const { userId } = await auth()
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const { policy_id } = await params
  const format = req.nextUrl.searchParams.get("format") ?? "html"

  if (format !== "html" && format !== "markdown") {
    return NextResponse.json({ error: "format must be html or markdown" }, { status: 400 })
  }

  const supabase = await createServerClient()
  const { data: policy, error } = await supabase
    .from("policies")
    .select("id, title, content_html, content_markdown, policy_type, status")
    .eq("id", policy_id)
    .single()

  if (error || !policy) {
    return NextResponse.json({ error: "Policy not found" }, { status: 404 })
  }

  if (policy.status !== "active") {
    return NextResponse.json({ error: "Policy is not ready for export" }, { status: 400 })
  }

  const safeTitle = (policy.title ?? "policy")
    .replace(/[^a-zA-Z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .toLowerCase()

  if (format === "markdown") {
    const markdown =
      policy.content_markdown ?? htmlToMarkdown(policy.content_html ?? "")
    return new NextResponse(markdown, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="${safeTitle}.md"`,
      },
    })
  }

  const html = wrapHtmlDocument(policy.title ?? "Policy", policy.content_html ?? "")
  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${safeTitle}.html"`,
    },
  })
}
