import { notFound } from "next/navigation"
import type { Metadata } from "next"
import { getPublicPolicy } from "@/lib/db/dal"
import type { PolicyType } from "@/types/supabase"
import PrintButton from "@/components/PrintButton"

export const revalidate = 3600

const URL_TO_DB: Record<string, PolicyType> = {
  "privacy-policy": "privacy_policy",
  "terms-of-service": "terms_of_service",
  "cookie-policy": "cookie_policy",
  "refund-policy": "refund_policy",
}

const POLICY_LABELS: Record<string, string> = {
  privacy_policy: "Privacy Policy",
  terms_of_service: "Terms of Service",
  cookie_policy: "Cookie Policy",
  refund_policy: "Refund Policy",
  dpa: "Data Processing Agreement",
}

function formatDate(iso: string | null): string {
  if (!iso) return "—"
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string; policy_type: string }>
}): Promise<Metadata> {
  const { slug, policy_type } = await params
  const dbType = URL_TO_DB[policy_type]
  if (!dbType) return { title: "Policy" }

  const data = await getPublicPolicy(slug, dbType)
  if (!data) return { title: "Policy" }

  const label = POLICY_LABELS[dbType] ?? "Policy"
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://policypen.io"

  return {
    title: `${label} — ${data.product.name}`,
    description: `${label} for ${data.product.name}`,
    robots: "index, follow",
    alternates: {
      canonical: `${appUrl}/p/${slug}/${policy_type}`,
    },
  }
}

export default async function PublicPolicyPage({
  params,
}: {
  params: Promise<{ slug: string; policy_type: string }>
}) {
  const { slug, policy_type } = await params
  const dbType = URL_TO_DB[policy_type]
  if (!dbType) notFound()

  const data = await getPublicPolicy(slug, dbType)
  if (!data) notFound()

  const { product, policy } = data
  const label = POLICY_LABELS[policy.policy_type] ?? "Policy"
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://policypen.io"

  return (
    <div className="policy-doc">
      <link
        rel="canonical"
        href={`${appUrl}/p/${slug}/${policy_type}`}
      />
      <meta name="robots" content="index, follow" />

      <div className="policy-single-header">
        <h1>{label}</h1>
        <p style={{ fontSize: 14, color: "var(--muted)", marginBottom: 4 }}>
          {product.name}
          {product.website_url && (
            <>
              {" · "}
              <a
                href={product.website_url}
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "var(--muted)" }}
              >
                {product.website_url}
              </a>
            </>
          )}
        </p>
      </div>

      <div className="policy-meta">
        <span>Last updated: {formatDate(policy.published_at ?? policy.updated_at)}</span>
        <span>Version {policy.version}</span>
        <PrintButton />
      </div>

      <div
        className="policy-content"
        dangerouslySetInnerHTML={{ __html: policy.content_html ?? "" }}
      />

      <div className="policy-attribution">
        Generated by{" "}
        <a href="https://policypen.io" target="_blank" rel="noopener noreferrer">
          PolicyPen
        </a>
      </div>
    </div>
  )
}
