import { getProductByCustomDomain } from "@/lib/db/dal"
import PolicyTabs from "@/app/p/[slug]/PolicyTabs"

export const revalidate = 3600

export async function generateMetadata({
  params,
}: {
  params: Promise<{ host: string }>
}) {
  const { host } = await params
  const domain = decodeURIComponent(host)
  const data = await getProductByCustomDomain(domain)
  if (!data) return { title: "Policies" }
  return {
    title: `${data.product.name} — Policies`,
    description: `Legal policies for ${data.product.name}`,
    robots: "index, follow",
  }
}

export default async function CustomDomainProductPage({
  params,
}: {
  params: Promise<{ host: string }>
}) {
  const { host } = await params
  const domain = decodeURIComponent(host)
  const data = await getProductByCustomDomain(domain)

  if (!data) {
    return (
      <div className="policy-doc">
        <div className="policy-product-header">
          <h1 className="policy-product-name">Domain not verified</h1>
          <p style={{ color: "var(--muted)", marginTop: 8 }}>
            This domain has not been verified yet. If you are the owner, please
            complete the DNS verification in your PolicyPen dashboard.
          </p>
        </div>
        <div className="policy-attribution">
          Powered by{" "}
          <a href="https://policypen.io" target="_blank" rel="noopener noreferrer">
            PolicyPen
          </a>
        </div>
      </div>
    )
  }

  const { product, policies } = data

  return (
    <div className="policy-doc">
      <div className="policy-product-header">
        <h1 className="policy-product-name">{product.name}</h1>
        {product.website_url && (
          <a
            href={product.website_url}
            target="_blank"
            rel="noopener noreferrer"
            className="policy-product-url"
          >
            {product.website_url}
          </a>
        )}
      </div>

      <PolicyTabs policies={policies} />

      <div className="policy-attribution">
        Generated by{" "}
        <a href="https://policypen.io" target="_blank" rel="noopener noreferrer">
          PolicyPen
        </a>
      </div>
    </div>
  )
}
