import { notFound } from "next/navigation"
import { getPublicProduct } from "@/lib/db/dal"
import PolicyTabs from "./PolicyTabs"

export const revalidate = 3600 // ISR — revalidate every hour

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const data = await getPublicProduct(slug)
  if (!data) return { title: "Policies" }
  return {
    title: `${data.product.name} — Policies`,
    description: `Legal policies for ${data.product.name}`,
    robots: "index, follow",
  }
}

export default async function PublicProductPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const data = await getPublicProduct(slug)
  if (!data) notFound()

  const { product, policies } = data

  return (
    <div className="policy-doc">
      <div className="policy-product-header">
        <h1 className="policy-product-name">{product.name}</h1>
        {product.website_url && (
          <a
            href={product.website_url}
            target="_blank"
            rel="noopener noreferrer"
            className="policy-product-url"
          >
            {product.website_url}
          </a>
        )}
      </div>

      <PolicyTabs policies={policies} />

      <div className="policy-attribution">
        Generated by{" "}
        <a href="https://policypen.io" target="_blank" rel="noopener noreferrer">
          PolicyPen
        </a>
      </div>
    </div>
  )
}
